# Generated by Django 2.0.9 on 2018-12-19 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups_manager', '0004_0_6_0_groupmember_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='codename',
            field=models.SlugField(blank=True, max_length=255, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='group',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='django_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='django group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_entities',
            field=models.ManyToManyField(blank=True, related_name='groups_manager_group_set', to='groups_manager.GroupEntity', verbose_name='group entities'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(related_name='groups_manager_group_set', through='groups_manager.GroupMember', to='groups_manager.Member', verbose_name='group members'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_manager_group_set', to='groups_manager.GroupType', verbose_name='group type'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups_manager_group_set', to='groups_manager.Group', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='group',
            name='properties',
            field=jsonfield.fields.JSONField(blank=True, default={}, verbose_name='properties'),
        ),
        migrations.AlterField(
            model_name='groupentity',
            name='codename',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='groupentity',
            name='label',
            field=models.CharField(max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to='groups_manager.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to='groups_manager.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='roles',
            field=models.ManyToManyField(blank=True, to='groups_manager.GroupMemberRole', verbose_name='roles'),
        ),
        migrations.AlterField(
            model_name='groupmemberrole',
            name='codename',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='groupmemberrole',
            name='label',
            field=models.CharField(max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='codename',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='label',
            field=models.CharField(max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='member',
            name='django_auth_sync',
            field=models.BooleanField(default=True, verbose_name='django auth sync'),
        ),
        migrations.AlterField(
            model_name='member',
            name='django_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_manager_member_set', to=settings.AUTH_USER_MODEL, verbose_name='django user'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='username'),
        ),
    ]
