# Generated by Django 4.2.1 on 2023-06-12 19:04
# using django-mptt 0.14.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups_manager", "0006_1_0_0_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_entities",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_set",
                to="groups_manager.groupentity",
                verbose_name="group entities",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_members",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_set",
                through="groups_manager.GroupMember",
                to="groups_manager.member",
                verbose_name="group members",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="groups_manager.grouptype",
                verbose_name="group type",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_%(app_label)s_%(class)s_set",
                to="groups_manager.group",
                verbose_name="parent",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="django_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="django user",
            ),
        ),
    ]
